### ISSUE TITLE
Create _spark_metadata

### ISSUE THREAD

**Issue by jozefbakus** [AbsaOSS/spark-metadata-tool#55]
## Background
A tool that helps us to create **_spark_metadata**  folder and metadata files. 
First version assumes checkpoint for data exists and contains at least one microbatch.
**How spark structured streaming works:**
> Spark structured streaming runs in microbatch fashion 
> In every microbatch spark reads portion of data and process them
> Every non-empty microbatch is numbered. Microbatches are monotonically increasing even between job restarts starting with 0 
> In every non-empty microbatch spark creates multiple files in different folders:
> -  **checkpoint** folder with **commits, metadata, offsets, sources** subfolders: 
>    - **offsets** folder: For every microbatch: creates file with microbatch number name that contains offsets from which job read data
>    - **commits** folder: For every successfully written offsets creates files with microbatch number name.
> -  **data destination** folder (in case of file data writer) - along with written data spark creates files in **_spark_metadata** subfolder: /destinatnion/_spark_metadata/0 ,  /destinatnion/_spark_metadata/1, ... (for every microbatch creates file with microbatch number name):
>    - every file contains references to written data and always starts with **v1**. Example: 
> `v1
{"path":"hdfs://absolutePathToFile/fileName1.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632046,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://absolutePathToFile/fileName1.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`
>     - During writing metadata spark does metadata file compaction for N last files (by default 10, can be changed). Example with metadata compaction set to 3: **0, 1, 2.compact, 3, 4, 5.compact, 6, 7, 8.compact, 9, 10, 11.compact, 12, 13**
>       - Files **0, 1, 2.compact, 3, 4, 5.compact, 6, 7, 8.compact, 9, 10** are irrelevant and will be eventually deleted by spark 
>       - **11.compact** file contains all records from previous files: **8.compact, 9, 10** compacted into it and newly written data files references. 
>       -  **12, 13** files contains newly written data files references

## Feature
Goal of this feature is to create tool that creates **_spark_metadata** folder under **destination** folder.
It should fail if: 
- destination folder does not exist or destination folder is empty
- _spark_metadata folder already exists 

Input should be: 
- **Data folder path**
- **Max microbatch number**
- **Compaction number**

## Example 1:
Data folder path: /destination/
Data folder contains files: f1.snappy.parquet, f2.snappy.parquet, f3.snappy.parquet, f4.snappy.parquet, f5.snappy.parquet, f6.snappy.parquet, f7.snappy.parquet, f8.snappy.parquet, f9.snappy.parquet, f10.snappy.parquet

Tool input: 
- **Data folder path**: /destination
- **Max microbatch number**: 9 
- **Compaction number**: 3

Tool result:
It will create **_spark_metadata** folder with following files (no need to create files: 0, 1, 2.compact 3 4 5.compact 6 7): 
8.compact, 9
Content of files:
- 8.compact: 
> `v1
{"path":"hdfs://destination/f1.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632046,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f2.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f3.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f4.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f5.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f6.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f7.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f8.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f9.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`

- 9: 
> `v1
{"path":"hdfs://destination/f10.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`

## Example 2:
Data folder path: /destination/
Data folder contains files: f1.snappy.parquet, f2.snappy.parquet, f3.snappy.parquet
Tool input: 
- **Data folder path**: /destination
- **Max microbatch number**: 2 
- **Compaction number**: 3

Tool result:
It will create **_spark_metadata** folder with following files: 
0, 1
Content of files:
- 0: 
> `v1
{"path":"hdfs://destination/f1.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632046,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f2.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`

- 1: 
> `v1
{"path":"hdfs://destination/f3.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`

## Example 3:
Data folder path: /destination/
Data folder contains files: f1.snappy.parquet, f2.snappy.parquet, f3.snappy.parquet, f4.snappy.parquet, f5.snappy.parquet, f6.snappy.parquet, f7.snappy.parquet, f8.snappy.parquet, f9.snappy.parquet, f10.snappy.parquet

Tool input: 
- **Data folder path**: /destination
- **Max microbatch number**: 8 
- **Compaction number**: 3

Tool result:
It will create **_spark_metadata** folder with following files (no need to create files: 0, 1, 2.compact 3 4 5.compact 6 7): 
8.compact
Content of files:
- 8.compact: 
> `v1
{"path":"hdfs://destination/f1.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632046,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f2.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f3.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f4.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f5.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f6.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f7.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f8.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f9.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}
{"path":"hdfs://destination/f10.snappy.parquet","size":8884,"isDir":false,"modificationTime":1672752632047,"blockReplication":3,"blockSize":134217728,"action":"add"}`

**Comment by filiphornak** [comment]
It's tested and it works on all storages, however I have question about the `--max-micro-batch-number`. How should the tool behave when the number doesn't match the number of files in directory? Current implementation **trims** the size of files to provided **max microbatch number** and then adds all the files up to **last compaction number** to `_spark_metadata/<last_compaction_number>.compact` and the rest is written in non compacted metadata files.
However this feels horribly wrong.

Wouldn't it be much better ignore the max micro batch number option? Or should I rather create metadata files up to max compaction number and rest should be written in compacted metadata? Wouldn't there be issue when compacted metadata are empty?

Lets have 25 data files in directory. Here are options, that came to my mind with some counter examples:

**Option 1** (Ignore `--max-micro-batch-number`)

**max micro batch number** is derived from number of part files in directory. Everything should work as expected, only one disadvantage is that you are unable to change `max-micro-batch-number` if you need to. Which is not really an counter example.

**Option 2** (aligned to `--max-micro-batch-number`)

There is guarantee that we have always latest metadata file with name `_spark_metadata/<max_micro_batch_number>`. There is also sequence of metadata files from `<last_compaction>.compat .. <max_micro_batch_number>`,
where each metadata file contains exactly one entry and compaction file contains the rest (which might be 0 entries).

Counter example: let's set `--compaction-number 50 --max-micro-batch-number 80`. This will create non compacted metadata files `55 .. 80`. There would be no compacted metadata file, even there should be.
